collections:
  default:
    output: true
    permalink: /default/:title/
    directory: "_default"  



title: 개미굴
description: GeamiGeami


url: "https://gaemigaemi.github.io" 


plugins:
  - jekyll-feed
  - jekyll-seo-tag